services:
  appfrontend:
    build:
      context: ./appfrontend
      dockerfile: Dockerfile
    container_name: app-frontend
    ports:
      - "8080:8080" 
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_SERVERS}
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${DB_DDL_AUTO}
      - APP_JWT_SECRET=${JWT_SECRET}
      - JAVA_OPTS=${JAVA_MEMORY_OPTS}
    depends_on:
      kafka:
        condition: service_started
      postgres-db:
        condition: service_healthy
    networks:
      - pos-network
    restart: always

  appbackend:
    build:
      context: ./appbackend
      dockerfile: Dockerfile
    container_name: app-backend
    ports:
      - "8082:8080" 
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_SERVERS}
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${DB_DDL_AUTO}
      - APP_JWT_SECRET=${JWT_SECRET}
      - JAVA_OPTS=${JAVA_MEMORY_OPTS}
    depends_on:
      kafka:
        condition: service_started
      postgres-db:
        condition: service_healthy
    networks:
      - pos-network
    restart: always

  # --- Database ---
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: pos_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d pos_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pos-network

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - pos-network

  kafbat-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    container_name: kafbat-ui
    ports:
      - "8081:8080" 
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
      - kafka
    networks:
      - pos-network

networks:
  pos-network:
    driver: bridge

volumes:
  postgres_data: