services:
  appfrontend:
    build:
      context: ./appfrontend
      dockerfile: Dockerfile
    container_name: app-frontend
    ports:
      - "8080:8080" 
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/pos_db
      - SPRING_DATASOURCE_USERNAME=savero
      - SPRING_DATASOURCE_PASSWORD=rahasia
      - JWT_SECRET=z2C8bY9vK7mN4pQ3rT6wX1yZ0sD2fG5hJ8kL9mN4pQ3rT6wX1yZ0sD2fG5hJ8kL9
      - JAVA_OPTS=-Xmx384M -Xms256M
    depends_on:
      kafka:
        condition: service_started
      postgres-db:
        condition: service_healthy
    networks:
      - pos-network

  appbackend:
    build:
      context: ./appbackend
      dockerfile: Dockerfile
    container_name: app-backend
    ports:
      - "8082:8080" 
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/pos_db
      - SPRING_DATASOURCE_USERNAME=atherizz
      - SPRING_DATASOURCE_PASSWORD=rahasia
      - JWT_SECRET=ganti_dengan_key_kamu_yang_panjang_dan_aman
      - JAVA_OPTS=-Xmx384M -Xms256M
    depends_on:
      kafka:
        condition: service_started
      postgres-db:
        condition: service_healthy
    networks:
      - pos-network

  # --- Database ---
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: savero
      POSTGRES_PASSWORD: rahasia
      POSTGRES_DB: pos_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U savero -d pos_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pos-network

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - pos-network

  kafbat-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    container_name: kafbat-ui
    ports:
      - "8081:8080" 
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
      - kafka
    networks:
      - pos-network

networks:
  pos-network:
    driver: bridge

volumes:
  postgres_data: